### ISSUE TITLE
machines/breakdown mill

### ISSUE THREAD

**Issue by pandrr** [undefined-development/PSIVR#2]
- breakdown mill == roughing mill in the thyssen krupp video
- breakdown mill == roughing mill = ignore the first part which looks like it is compressing the slab

- check reference with 3 parts, rollers, visible process

- machine heights: 3-4m

**Comment by androvisuals** [comment]
Breakdown mill and coiler models are done with there first versions

**Comment by androvisuals** [comment]
Closed.
