### ISSUE TITLE
Test animations with FBX, DAE and blend files

### ISSUE THREAD

**Issue by androvisuals** [undefined-development/PSIVR#6]

**Comment by androvisuals** [comment]
Bkaed animations in models don't play correctly in cables, they seem to play very slowly.
Files are in the drop folder

![image](https://user-images.githubusercontent.com/19530188/55557992-6bf48100-56eb-11e9-8143-40f1406cf7f6.png)

Theres a DAE, FBX and blend file in there.

There are 3 cubes which have the plane as a parent. All 3 cubes are animated.
2 move and rotate, the 3rd one just rotates and should be able to loop perfectly.
All animations were baked into each object in blender.
These need to work correctly with time inside of cables.
Blender was set to 25 fps and the total length of the animation is 150 frames.

Collada : DAE settings in blender

![image](https://user-images.githubusercontent.com/19530188/55557917-3780c500-56eb-11e9-9d0e-110a7e3b6abb.png)

FBX settings
![image](https://user-images.githubusercontent.com/19530188/55558387-40be6180-56ec-11e9-9229-d9e8b4d213e1.png)

![image](https://user-images.githubusercontent.com/19530188/55558403-4f0c7d80-56ec-11e9-8ba5-7b7349444e13.png)

![image](https://user-images.githubusercontent.com/19530188/55558420-5af83f80-56ec-11e9-88ce-dc2e0444aeb8.png)

![image](https://user-images.githubusercontent.com/19530188/55558447-6481a780-56ec-11e9-816f-a759cea652e0.png)

**Comment by pandrr** [comment]
ok i got it working now!

we need to use collada files.

in the export settings, you have to switch transformation type to TransRotLoc

then it plays back fine!

**Comment by pandrr** [comment]
the scaled cubes are wrong somehow, probably the nonskalar scale has some probelms, we should not have that problem with normal meshes, i hope. 
lets try!

**Comment by androvisuals** [comment]
Closed
